# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: build.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='build.proto',
  package='rqt2.api.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x62uild.proto\x12\x0brqt2.api.v1\x1a\x0btypes.proto\"\xc3\x01\n\x0c\x42uildRequest\x12\x16\n\x0eworkspace_path\x18\x01 \x01(\t\x12\x10\n\x08packages\x18\x02 \x03(\t\x12\x13\n\x0b\x63olcon_args\x18\x03 \x03(\t\x12\x17\n\x0fsymlink_install\x18\x04 \x01(\x08\x12/\n\x03\x65nv\x18\x05 \x03(\x0b\x32\".rqt2.api.v1.BuildRequest.EnvEntry\x1a*\n\x08\x45nvEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x96\x01\n\nBuildEvent\x12$\n\x03log\x18\x01 \x01(\x0b\x32\x15.rqt2.api.v1.LogEntryH\x00\x12%\n\x06status\x18\x02 \x01(\x0b\x32\x13.rqt2.api.v1.StatusH\x00\x12\x19\n\x0f\x63urrent_package\x18\x03 \x01(\tH\x00\x12\x1a\n\x10progress_percent\x18\x04 \x01(\x01H\x00\x42\x04\n\x02\x65v\"M\n\x0c\x43leanRequest\x12\x13\n\x0b\x63lean_build\x18\x01 \x01(\x08\x12\x15\n\rclean_install\x18\x02 \x01(\x08\x12\x11\n\tclean_log\x18\x03 \x01(\x08\"2\n\x0bLoadRequest\x12\r\n\x05shell\x18\x01 \x01(\t\x12\x14\n\x0coverlay_path\x18\x02 \x01(\t2\xd6\x01\n\x0c\x42uildService\x12\x46\n\x0e\x42uildWorkspace\x12\x19.rqt2.api.v1.BuildRequest\x1a\x17.rqt2.api.v1.BuildEvent0\x01\x12@\n\x0e\x43leanWorkspace\x12\x19.rqt2.api.v1.CleanRequest\x1a\x13.rqt2.api.v1.Status\x12<\n\x0bLoadOverlay\x12\x18.rqt2.api.v1.LoadRequest\x1a\x13.rqt2.api.v1.Statusb\x06proto3')
  ,
  dependencies=[types__pb2.DESCRIPTOR,])




_BUILDREQUEST_ENVENTRY = _descriptor.Descriptor(
  name='EnvEntry',
  full_name='rqt2.api.v1.BuildRequest.EnvEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='rqt2.api.v1.BuildRequest.EnvEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='rqt2.api.v1.BuildRequest.EnvEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=237,
)

_BUILDREQUEST = _descriptor.Descriptor(
  name='BuildRequest',
  full_name='rqt2.api.v1.BuildRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workspace_path', full_name='rqt2.api.v1.BuildRequest.workspace_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packages', full_name='rqt2.api.v1.BuildRequest.packages', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colcon_args', full_name='rqt2.api.v1.BuildRequest.colcon_args', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symlink_install', full_name='rqt2.api.v1.BuildRequest.symlink_install', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='env', full_name='rqt2.api.v1.BuildRequest.env', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BUILDREQUEST_ENVENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=237,
)


_BUILDEVENT = _descriptor.Descriptor(
  name='BuildEvent',
  full_name='rqt2.api.v1.BuildEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='log', full_name='rqt2.api.v1.BuildEvent.log', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='rqt2.api.v1.BuildEvent.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_package', full_name='rqt2.api.v1.BuildEvent.current_package', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='progress_percent', full_name='rqt2.api.v1.BuildEvent.progress_percent', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='ev', full_name='rqt2.api.v1.BuildEvent.ev',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=240,
  serialized_end=390,
)


_CLEANREQUEST = _descriptor.Descriptor(
  name='CleanRequest',
  full_name='rqt2.api.v1.CleanRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clean_build', full_name='rqt2.api.v1.CleanRequest.clean_build', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clean_install', full_name='rqt2.api.v1.CleanRequest.clean_install', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clean_log', full_name='rqt2.api.v1.CleanRequest.clean_log', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=469,
)


_LOADREQUEST = _descriptor.Descriptor(
  name='LoadRequest',
  full_name='rqt2.api.v1.LoadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shell', full_name='rqt2.api.v1.LoadRequest.shell', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='overlay_path', full_name='rqt2.api.v1.LoadRequest.overlay_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=521,
)

_BUILDREQUEST_ENVENTRY.containing_type = _BUILDREQUEST
_BUILDREQUEST.fields_by_name['env'].message_type = _BUILDREQUEST_ENVENTRY
_BUILDEVENT.fields_by_name['log'].message_type = types__pb2._LOGENTRY
_BUILDEVENT.fields_by_name['status'].message_type = types__pb2._STATUS
_BUILDEVENT.oneofs_by_name['ev'].fields.append(
  _BUILDEVENT.fields_by_name['log'])
_BUILDEVENT.fields_by_name['log'].containing_oneof = _BUILDEVENT.oneofs_by_name['ev']
_BUILDEVENT.oneofs_by_name['ev'].fields.append(
  _BUILDEVENT.fields_by_name['status'])
_BUILDEVENT.fields_by_name['status'].containing_oneof = _BUILDEVENT.oneofs_by_name['ev']
_BUILDEVENT.oneofs_by_name['ev'].fields.append(
  _BUILDEVENT.fields_by_name['current_package'])
_BUILDEVENT.fields_by_name['current_package'].containing_oneof = _BUILDEVENT.oneofs_by_name['ev']
_BUILDEVENT.oneofs_by_name['ev'].fields.append(
  _BUILDEVENT.fields_by_name['progress_percent'])
_BUILDEVENT.fields_by_name['progress_percent'].containing_oneof = _BUILDEVENT.oneofs_by_name['ev']
DESCRIPTOR.message_types_by_name['BuildRequest'] = _BUILDREQUEST
DESCRIPTOR.message_types_by_name['BuildEvent'] = _BUILDEVENT
DESCRIPTOR.message_types_by_name['CleanRequest'] = _CLEANREQUEST
DESCRIPTOR.message_types_by_name['LoadRequest'] = _LOADREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuildRequest = _reflection.GeneratedProtocolMessageType('BuildRequest', (_message.Message,), dict(

  EnvEntry = _reflection.GeneratedProtocolMessageType('EnvEntry', (_message.Message,), dict(
    DESCRIPTOR = _BUILDREQUEST_ENVENTRY,
    __module__ = 'build_pb2'
    # @@protoc_insertion_point(class_scope:rqt2.api.v1.BuildRequest.EnvEntry)
    ))
  ,
  DESCRIPTOR = _BUILDREQUEST,
  __module__ = 'build_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.BuildRequest)
  ))
_sym_db.RegisterMessage(BuildRequest)
_sym_db.RegisterMessage(BuildRequest.EnvEntry)

BuildEvent = _reflection.GeneratedProtocolMessageType('BuildEvent', (_message.Message,), dict(
  DESCRIPTOR = _BUILDEVENT,
  __module__ = 'build_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.BuildEvent)
  ))
_sym_db.RegisterMessage(BuildEvent)

CleanRequest = _reflection.GeneratedProtocolMessageType('CleanRequest', (_message.Message,), dict(
  DESCRIPTOR = _CLEANREQUEST,
  __module__ = 'build_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.CleanRequest)
  ))
_sym_db.RegisterMessage(CleanRequest)

LoadRequest = _reflection.GeneratedProtocolMessageType('LoadRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOADREQUEST,
  __module__ = 'build_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.LoadRequest)
  ))
_sym_db.RegisterMessage(LoadRequest)


_BUILDREQUEST_ENVENTRY.has_options = True
_BUILDREQUEST_ENVENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_BUILDSERVICE = _descriptor.ServiceDescriptor(
  name='BuildService',
  full_name='rqt2.api.v1.BuildService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=524,
  serialized_end=738,
  methods=[
  _descriptor.MethodDescriptor(
    name='BuildWorkspace',
    full_name='rqt2.api.v1.BuildService.BuildWorkspace',
    index=0,
    containing_service=None,
    input_type=_BUILDREQUEST,
    output_type=_BUILDEVENT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CleanWorkspace',
    full_name='rqt2.api.v1.BuildService.CleanWorkspace',
    index=1,
    containing_service=None,
    input_type=_CLEANREQUEST,
    output_type=types__pb2._STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LoadOverlay',
    full_name='rqt2.api.v1.BuildService.LoadOverlay',
    index=2,
    containing_service=None,
    input_type=_LOADREQUEST,
    output_type=types__pb2._STATUS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BUILDSERVICE)

DESCRIPTOR.services_by_name['BuildService'] = _BUILDSERVICE

# @@protoc_insertion_point(module_scope)
