# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import build_pb2 as build__pb2
import types_pb2 as types__pb2


class BuildServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.BuildWorkspace = channel.unary_stream(
        '/rqt2.api.v1.BuildService/BuildWorkspace',
        request_serializer=build__pb2.BuildRequest.SerializeToString,
        response_deserializer=build__pb2.BuildEvent.FromString,
        )
    self.CleanWorkspace = channel.unary_unary(
        '/rqt2.api.v1.BuildService/CleanWorkspace',
        request_serializer=build__pb2.CleanRequest.SerializeToString,
        response_deserializer=types__pb2.Status.FromString,
        )
    self.LoadOverlay = channel.unary_unary(
        '/rqt2.api.v1.BuildService/LoadOverlay',
        request_serializer=build__pb2.LoadRequest.SerializeToString,
        response_deserializer=types__pb2.Status.FromString,
        )


class BuildServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def BuildWorkspace(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CleanWorkspace(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LoadOverlay(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BuildServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'BuildWorkspace': grpc.unary_stream_rpc_method_handler(
          servicer.BuildWorkspace,
          request_deserializer=build__pb2.BuildRequest.FromString,
          response_serializer=build__pb2.BuildEvent.SerializeToString,
      ),
      'CleanWorkspace': grpc.unary_unary_rpc_method_handler(
          servicer.CleanWorkspace,
          request_deserializer=build__pb2.CleanRequest.FromString,
          response_serializer=types__pb2.Status.SerializeToString,
      ),
      'LoadOverlay': grpc.unary_unary_rpc_method_handler(
          servicer.LoadOverlay,
          request_deserializer=build__pb2.LoadRequest.FromString,
          response_serializer=types__pb2.Status.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rqt2.api.v1.BuildService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
