# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clone_ws.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='clone_ws.proto',
  package='rqt2.api.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x63lone_ws.proto\x12\x0brqt2.api.v1\"\x7f\n\x15\x43loneWorkspaceRequest\x12\x16\n\x0erepository_url\x18\x01 \x01(\t\x12\x17\n\x0f\x64\x65stination_dir\x18\x02 \x01(\t\x12\x16\n\x0eworkspace_name\x18\x03 \x01(\t\x12\x0e\n\x06\x62ranch\x18\x04 \x01(\t\x12\r\n\x05\x64\x65pth\x18\x05 \x01(\r\"`\n\x16\x43loneWorkspaceProgress\x12\x10\n\x08log_line\x18\x01 \x01(\t\x12\x10\n\x08progress\x18\x02 \x01(\x02\x12\x11\n\tcompleted\x18\x03 \x01(\x08\x12\x0f\n\x07success\x18\x04 \x01(\x08\x32t\n\x15\x43loneWorkspaceService\x12[\n\x0e\x43loneWorkspace\x12\".rqt2.api.v1.CloneWorkspaceRequest\x1a#.rqt2.api.v1.CloneWorkspaceProgress0\x01\x62\x06proto3')
)




_CLONEWORKSPACEREQUEST = _descriptor.Descriptor(
  name='CloneWorkspaceRequest',
  full_name='rqt2.api.v1.CloneWorkspaceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='repository_url', full_name='rqt2.api.v1.CloneWorkspaceRequest.repository_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination_dir', full_name='rqt2.api.v1.CloneWorkspaceRequest.destination_dir', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workspace_name', full_name='rqt2.api.v1.CloneWorkspaceRequest.workspace_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='branch', full_name='rqt2.api.v1.CloneWorkspaceRequest.branch', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth', full_name='rqt2.api.v1.CloneWorkspaceRequest.depth', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=158,
)


_CLONEWORKSPACEPROGRESS = _descriptor.Descriptor(
  name='CloneWorkspaceProgress',
  full_name='rqt2.api.v1.CloneWorkspaceProgress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='log_line', full_name='rqt2.api.v1.CloneWorkspaceProgress.log_line', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='progress', full_name='rqt2.api.v1.CloneWorkspaceProgress.progress', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='completed', full_name='rqt2.api.v1.CloneWorkspaceProgress.completed', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='success', full_name='rqt2.api.v1.CloneWorkspaceProgress.success', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=256,
)

DESCRIPTOR.message_types_by_name['CloneWorkspaceRequest'] = _CLONEWORKSPACEREQUEST
DESCRIPTOR.message_types_by_name['CloneWorkspaceProgress'] = _CLONEWORKSPACEPROGRESS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CloneWorkspaceRequest = _reflection.GeneratedProtocolMessageType('CloneWorkspaceRequest', (_message.Message,), dict(
  DESCRIPTOR = _CLONEWORKSPACEREQUEST,
  __module__ = 'clone_ws_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.CloneWorkspaceRequest)
  ))
_sym_db.RegisterMessage(CloneWorkspaceRequest)

CloneWorkspaceProgress = _reflection.GeneratedProtocolMessageType('CloneWorkspaceProgress', (_message.Message,), dict(
  DESCRIPTOR = _CLONEWORKSPACEPROGRESS,
  __module__ = 'clone_ws_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.CloneWorkspaceProgress)
  ))
_sym_db.RegisterMessage(CloneWorkspaceProgress)



_CLONEWORKSPACESERVICE = _descriptor.ServiceDescriptor(
  name='CloneWorkspaceService',
  full_name='rqt2.api.v1.CloneWorkspaceService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=258,
  serialized_end=374,
  methods=[
  _descriptor.MethodDescriptor(
    name='CloneWorkspace',
    full_name='rqt2.api.v1.CloneWorkspaceService.CloneWorkspace',
    index=0,
    containing_service=None,
    input_type=_CLONEWORKSPACEREQUEST,
    output_type=_CLONEWORKSPACEPROGRESS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLONEWORKSPACESERVICE)

DESCRIPTOR.services_by_name['CloneWorkspaceService'] = _CLONEWORKSPACESERVICE

# @@protoc_insertion_point(module_scope)
