# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import clone_ws_pb2 as clone__ws__pb2


class CloneWorkspaceServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CloneWorkspace = channel.unary_stream(
        '/rqt2.api.v1.CloneWorkspaceService/CloneWorkspace',
        request_serializer=clone__ws__pb2.CloneWorkspaceRequest.SerializeToString,
        response_deserializer=clone__ws__pb2.CloneWorkspaceProgress.FromString,
        )


class CloneWorkspaceServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CloneWorkspace(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CloneWorkspaceServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CloneWorkspace': grpc.unary_stream_rpc_method_handler(
          servicer.CloneWorkspace,
          request_deserializer=clone__ws__pb2.CloneWorkspaceRequest.FromString,
          response_serializer=clone__ws__pb2.CloneWorkspaceProgress.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rqt2.api.v1.CloneWorkspaceService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
