# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import data_stream_pb2 as data__stream__pb2
import types_pb2 as types__pb2


class DataStreamServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Subscribe = channel.unary_stream(
        '/rqt2.api.v1.DataStreamService/Subscribe',
        request_serializer=data__stream__pb2.SubscribeRequest.SerializeToString,
        response_deserializer=data__stream__pb2.TopicMessage.FromString,
        )
    self.Publish = channel.unary_unary(
        '/rqt2.api.v1.DataStreamService/Publish',
        request_serializer=data__stream__pb2.PublishRequest.SerializeToString,
        response_deserializer=types__pb2.Status.FromString,
        )
    self.Record = channel.unary_stream(
        '/rqt2.api.v1.DataStreamService/Record',
        request_serializer=data__stream__pb2.RecordRequest.SerializeToString,
        response_deserializer=data__stream__pb2.RecordEvent.FromString,
        )
    self.Play = channel.unary_stream(
        '/rqt2.api.v1.DataStreamService/Play',
        request_serializer=data__stream__pb2.PlayRequest.SerializeToString,
        response_deserializer=data__stream__pb2.PlaybackEvent.FromString,
        )


class DataStreamServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Subscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Publish(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Record(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Play(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DataStreamServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=data__stream__pb2.SubscribeRequest.FromString,
          response_serializer=data__stream__pb2.TopicMessage.SerializeToString,
      ),
      'Publish': grpc.unary_unary_rpc_method_handler(
          servicer.Publish,
          request_deserializer=data__stream__pb2.PublishRequest.FromString,
          response_serializer=types__pb2.Status.SerializeToString,
      ),
      'Record': grpc.unary_stream_rpc_method_handler(
          servicer.Record,
          request_deserializer=data__stream__pb2.RecordRequest.FromString,
          response_serializer=data__stream__pb2.RecordEvent.SerializeToString,
      ),
      'Play': grpc.unary_stream_rpc_method_handler(
          servicer.Play,
          request_deserializer=data__stream__pb2.PlayRequest.FromString,
          response_serializer=data__stream__pb2.PlaybackEvent.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rqt2.api.v1.DataStreamService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
