# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import execution_pb2 as execution__pb2
import types_pb2 as types__pb2


class ExecutionServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Run = channel.unary_stream(
        '/rqt2.api.v1.ExecutionService/Run',
        request_serializer=execution__pb2.RunRequest.SerializeToString,
        response_deserializer=execution__pb2.ExecEvent.FromString,
        )
    self.Stop = channel.unary_unary(
        '/rqt2.api.v1.ExecutionService/Stop',
        request_serializer=execution__pb2.StopRequest.SerializeToString,
        response_deserializer=types__pb2.Status.FromString,
        )
    self.ListLaunchFiles = channel.unary_unary(
        '/rqt2.api.v1.ExecutionService/ListLaunchFiles',
        request_serializer=types__pb2.Empty.SerializeToString,
        response_deserializer=execution__pb2.LaunchListResponse.FromString,
        )


class ExecutionServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Run(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Stop(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListLaunchFiles(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ExecutionServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Run': grpc.unary_stream_rpc_method_handler(
          servicer.Run,
          request_deserializer=execution__pb2.RunRequest.FromString,
          response_serializer=execution__pb2.ExecEvent.SerializeToString,
      ),
      'Stop': grpc.unary_unary_rpc_method_handler(
          servicer.Stop,
          request_deserializer=execution__pb2.StopRequest.FromString,
          response_serializer=types__pb2.Status.SerializeToString,
      ),
      'ListLaunchFiles': grpc.unary_unary_rpc_method_handler(
          servicer.ListLaunchFiles,
          request_deserializer=types__pb2.Empty.FromString,
          response_serializer=execution__pb2.LaunchListResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rqt2.api.v1.ExecutionService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
