# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: execution.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='execution.proto',
  package='rqt2.api.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x65xecution.proto\x12\x0brqt2.api.v1\x1a\x0btypes.proto\"\xe2\x01\n\nRunRequest\x12\x0f\n\x07package\x18\x01 \x01(\t\x12\x12\n\nexecutable\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x03(\t\x12\x10\n\x08ros_args\x18\x04 \x03(\t\x12-\n\x03\x65nv\x18\x05 \x03(\x0b\x32 .rqt2.api.v1.RunRequest.EnvEntry\x12\x0b\n\x03\x63wd\x18\x06 \x01(\t\x12\x12\n\nuse_launch\x18\x07 \x01(\x08\x12\x13\n\x0blaunch_file\x18\x08 \x01(\t\x1a*\n\x08\x45nvEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"F\n\x0bStopRequest\x12\r\n\x03pid\x18\x01 \x01(\x05H\x00\x12\x13\n\tnode_name\x18\x02 \x01(\tH\x00\x12\r\n\x05\x66orce\x18\x03 \x01(\x08\x42\x04\n\x02\x65v\"s\n\tExecEvent\x12$\n\x03log\x18\x01 \x01(\x0b\x32\x15.rqt2.api.v1.LogEntryH\x00\x12%\n\x06status\x18\x02 \x01(\x0b\x32\x13.rqt2.api.v1.StatusH\x00\x12\x13\n\texit_code\x18\x03 \x01(\x05H\x00\x42\x04\n\x02\x65v\"O\n\x12LaunchListResponse\x12\x14\n\x0claunch_files\x18\x01 \x03(\t\x12#\n\x06status\x18\x02 \x01(\x0b\x32\x13.rqt2.api.v1.Status2\xcb\x01\n\x10\x45xecutionService\x12\x38\n\x03Run\x12\x17.rqt2.api.v1.RunRequest\x1a\x16.rqt2.api.v1.ExecEvent0\x01\x12\x35\n\x04Stop\x12\x18.rqt2.api.v1.StopRequest\x1a\x13.rqt2.api.v1.Status\x12\x46\n\x0fListLaunchFiles\x12\x12.rqt2.api.v1.Empty\x1a\x1f.rqt2.api.v1.LaunchListResponseb\x06proto3')
  ,
  dependencies=[types__pb2.DESCRIPTOR,])




_RUNREQUEST_ENVENTRY = _descriptor.Descriptor(
  name='EnvEntry',
  full_name='rqt2.api.v1.RunRequest.EnvEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='rqt2.api.v1.RunRequest.EnvEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='rqt2.api.v1.RunRequest.EnvEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=272,
)

_RUNREQUEST = _descriptor.Descriptor(
  name='RunRequest',
  full_name='rqt2.api.v1.RunRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='package', full_name='rqt2.api.v1.RunRequest.package', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='executable', full_name='rqt2.api.v1.RunRequest.executable', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='rqt2.api.v1.RunRequest.args', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ros_args', full_name='rqt2.api.v1.RunRequest.ros_args', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='env', full_name='rqt2.api.v1.RunRequest.env', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cwd', full_name='rqt2.api.v1.RunRequest.cwd', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_launch', full_name='rqt2.api.v1.RunRequest.use_launch', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='launch_file', full_name='rqt2.api.v1.RunRequest.launch_file', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RUNREQUEST_ENVENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=272,
)


_STOPREQUEST = _descriptor.Descriptor(
  name='StopRequest',
  full_name='rqt2.api.v1.StopRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='rqt2.api.v1.StopRequest.pid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_name', full_name='rqt2.api.v1.StopRequest.node_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='force', full_name='rqt2.api.v1.StopRequest.force', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='ev', full_name='rqt2.api.v1.StopRequest.ev',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=274,
  serialized_end=344,
)


_EXECEVENT = _descriptor.Descriptor(
  name='ExecEvent',
  full_name='rqt2.api.v1.ExecEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='log', full_name='rqt2.api.v1.ExecEvent.log', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='rqt2.api.v1.ExecEvent.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exit_code', full_name='rqt2.api.v1.ExecEvent.exit_code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='ev', full_name='rqt2.api.v1.ExecEvent.ev',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=346,
  serialized_end=461,
)


_LAUNCHLISTRESPONSE = _descriptor.Descriptor(
  name='LaunchListResponse',
  full_name='rqt2.api.v1.LaunchListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='launch_files', full_name='rqt2.api.v1.LaunchListResponse.launch_files', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='rqt2.api.v1.LaunchListResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=542,
)

_RUNREQUEST_ENVENTRY.containing_type = _RUNREQUEST
_RUNREQUEST.fields_by_name['env'].message_type = _RUNREQUEST_ENVENTRY
_STOPREQUEST.oneofs_by_name['ev'].fields.append(
  _STOPREQUEST.fields_by_name['pid'])
_STOPREQUEST.fields_by_name['pid'].containing_oneof = _STOPREQUEST.oneofs_by_name['ev']
_STOPREQUEST.oneofs_by_name['ev'].fields.append(
  _STOPREQUEST.fields_by_name['node_name'])
_STOPREQUEST.fields_by_name['node_name'].containing_oneof = _STOPREQUEST.oneofs_by_name['ev']
_EXECEVENT.fields_by_name['log'].message_type = types__pb2._LOGENTRY
_EXECEVENT.fields_by_name['status'].message_type = types__pb2._STATUS
_EXECEVENT.oneofs_by_name['ev'].fields.append(
  _EXECEVENT.fields_by_name['log'])
_EXECEVENT.fields_by_name['log'].containing_oneof = _EXECEVENT.oneofs_by_name['ev']
_EXECEVENT.oneofs_by_name['ev'].fields.append(
  _EXECEVENT.fields_by_name['status'])
_EXECEVENT.fields_by_name['status'].containing_oneof = _EXECEVENT.oneofs_by_name['ev']
_EXECEVENT.oneofs_by_name['ev'].fields.append(
  _EXECEVENT.fields_by_name['exit_code'])
_EXECEVENT.fields_by_name['exit_code'].containing_oneof = _EXECEVENT.oneofs_by_name['ev']
_LAUNCHLISTRESPONSE.fields_by_name['status'].message_type = types__pb2._STATUS
DESCRIPTOR.message_types_by_name['RunRequest'] = _RUNREQUEST
DESCRIPTOR.message_types_by_name['StopRequest'] = _STOPREQUEST
DESCRIPTOR.message_types_by_name['ExecEvent'] = _EXECEVENT
DESCRIPTOR.message_types_by_name['LaunchListResponse'] = _LAUNCHLISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RunRequest = _reflection.GeneratedProtocolMessageType('RunRequest', (_message.Message,), dict(

  EnvEntry = _reflection.GeneratedProtocolMessageType('EnvEntry', (_message.Message,), dict(
    DESCRIPTOR = _RUNREQUEST_ENVENTRY,
    __module__ = 'execution_pb2'
    # @@protoc_insertion_point(class_scope:rqt2.api.v1.RunRequest.EnvEntry)
    ))
  ,
  DESCRIPTOR = _RUNREQUEST,
  __module__ = 'execution_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.RunRequest)
  ))
_sym_db.RegisterMessage(RunRequest)
_sym_db.RegisterMessage(RunRequest.EnvEntry)

StopRequest = _reflection.GeneratedProtocolMessageType('StopRequest', (_message.Message,), dict(
  DESCRIPTOR = _STOPREQUEST,
  __module__ = 'execution_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.StopRequest)
  ))
_sym_db.RegisterMessage(StopRequest)

ExecEvent = _reflection.GeneratedProtocolMessageType('ExecEvent', (_message.Message,), dict(
  DESCRIPTOR = _EXECEVENT,
  __module__ = 'execution_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.ExecEvent)
  ))
_sym_db.RegisterMessage(ExecEvent)

LaunchListResponse = _reflection.GeneratedProtocolMessageType('LaunchListResponse', (_message.Message,), dict(
  DESCRIPTOR = _LAUNCHLISTRESPONSE,
  __module__ = 'execution_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.LaunchListResponse)
  ))
_sym_db.RegisterMessage(LaunchListResponse)


_RUNREQUEST_ENVENTRY.has_options = True
_RUNREQUEST_ENVENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_EXECUTIONSERVICE = _descriptor.ServiceDescriptor(
  name='ExecutionService',
  full_name='rqt2.api.v1.ExecutionService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=545,
  serialized_end=748,
  methods=[
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='rqt2.api.v1.ExecutionService.Run',
    index=0,
    containing_service=None,
    input_type=_RUNREQUEST,
    output_type=_EXECEVENT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Stop',
    full_name='rqt2.api.v1.ExecutionService.Stop',
    index=1,
    containing_service=None,
    input_type=_STOPREQUEST,
    output_type=types__pb2._STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListLaunchFiles',
    full_name='rqt2.api.v1.ExecutionService.ListLaunchFiles',
    index=2,
    containing_service=None,
    input_type=types__pb2._EMPTY,
    output_type=_LAUNCHLISTRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXECUTIONSERVICE)

DESCRIPTOR.services_by_name['ExecutionService'] = _EXECUTIONSERVICE

# @@protoc_insertion_point(module_scope)
