# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import file_system_pb2 as file__system__pb2
import types_pb2 as types__pb2


class FileServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Stat = channel.unary_unary(
        '/rqt2.api.v1.FileService/Stat',
        request_serializer=file__system__pb2.ReadFileRequest.SerializeToString,
        response_deserializer=file__system__pb2.FileInfo.FromString,
        )
    self.Read = channel.unary_unary(
        '/rqt2.api.v1.FileService/Read',
        request_serializer=file__system__pb2.ReadFileRequest.SerializeToString,
        response_deserializer=file__system__pb2.FileContent.FromString,
        )
    self.Write = channel.unary_unary(
        '/rqt2.api.v1.FileService/Write',
        request_serializer=file__system__pb2.WriteFileRequest.SerializeToString,
        response_deserializer=types__pb2.Status.FromString,
        )
    self.Delete = channel.unary_unary(
        '/rqt2.api.v1.FileService/Delete',
        request_serializer=file__system__pb2.ReadFileRequest.SerializeToString,
        response_deserializer=types__pb2.Status.FromString,
        )
    self.Rename = channel.unary_unary(
        '/rqt2.api.v1.FileService/Rename',
        request_serializer=file__system__pb2.RenameRequest.SerializeToString,
        response_deserializer=types__pb2.Status.FromString,
        )
    self.List = channel.unary_unary(
        '/rqt2.api.v1.FileService/List',
        request_serializer=file__system__pb2.PathRequest.SerializeToString,
        response_deserializer=file__system__pb2.ListFilesResponse.FromString,
        )
    self.Watch = channel.unary_stream(
        '/rqt2.api.v1.FileService/Watch',
        request_serializer=file__system__pb2.PathRequest.SerializeToString,
        response_deserializer=file__system__pb2.FileEvent.FromString,
        )


class FileServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Stat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Read(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Write(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Rename(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Watch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Stat': grpc.unary_unary_rpc_method_handler(
          servicer.Stat,
          request_deserializer=file__system__pb2.ReadFileRequest.FromString,
          response_serializer=file__system__pb2.FileInfo.SerializeToString,
      ),
      'Read': grpc.unary_unary_rpc_method_handler(
          servicer.Read,
          request_deserializer=file__system__pb2.ReadFileRequest.FromString,
          response_serializer=file__system__pb2.FileContent.SerializeToString,
      ),
      'Write': grpc.unary_unary_rpc_method_handler(
          servicer.Write,
          request_deserializer=file__system__pb2.WriteFileRequest.FromString,
          response_serializer=types__pb2.Status.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=file__system__pb2.ReadFileRequest.FromString,
          response_serializer=types__pb2.Status.SerializeToString,
      ),
      'Rename': grpc.unary_unary_rpc_method_handler(
          servicer.Rename,
          request_deserializer=file__system__pb2.RenameRequest.FromString,
          response_serializer=types__pb2.Status.SerializeToString,
      ),
      'List': grpc.unary_unary_rpc_method_handler(
          servicer.List,
          request_deserializer=file__system__pb2.PathRequest.FromString,
          response_serializer=file__system__pb2.ListFilesResponse.SerializeToString,
      ),
      'Watch': grpc.unary_stream_rpc_method_handler(
          servicer.Watch,
          request_deserializer=file__system__pb2.PathRequest.FromString,
          response_serializer=file__system__pb2.FileEvent.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rqt2.api.v1.FileService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
