# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: introspection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='introspection.proto',
  package='rqt2.api.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x13introspection.proto\x12\x0brqt2.api.v1\x1a\x0btypes.proto\"B\n\x13IntrospectionFilter\x12\x12\n\nnamespaces\x18\x01 \x03(\t\x12\x17\n\x0fnode_name_regex\x18\x02 \x01(\t\"\x80\x01\n\x11TopicInfoExtended\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0cmessage_type\x18\x02 \x01(\t\x12\x17\n\x0fpublisher_count\x18\x03 \x01(\x05\x12\x18\n\x10subscriber_count\x18\x04 \x01(\x05\x12\x14\n\x0cqos_profiles\x18\x05 \x03(\t\"^\n\x11ListNodesResponse\x12$\n\x05nodes\x18\x01 \x03(\x0b\x32\x15.rqt2.api.v1.NodeInfo\x12#\n\x06status\x18\x02 \x01(\x0b\x32\x13.rqt2.api.v1.Status\"i\n\x12ListTopicsResponse\x12.\n\x06topics\x18\x01 \x03(\x0b\x32\x1e.rqt2.api.v1.TopicInfoExtended\x12#\n\x06status\x18\x02 \x01(\x0b\x32\x13.rqt2.api.v1.Status\"\x92\x01\n\tNodeEvent\x12.\n\x04type\x18\x01 \x01(\x0e\x32 .rqt2.api.v1.NodeEvent.EventType\x12#\n\x04node\x18\x02 \x01(\x0b\x32\x15.rqt2.api.v1.NodeInfo\"0\n\tEventType\x12\t\n\x05\x41\x44\x44\x45\x44\x10\x00\x12\x0b\n\x07REMOVED\x10\x01\x12\x0b\n\x07UPDATED\x10\x02\"\x96\x01\n\nTopicEvent\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.rqt2.api.v1.TopicEvent.EventType\x12%\n\x05topic\x18\x02 \x01(\x0b\x32\x16.rqt2.api.v1.TopicInfo\"0\n\tEventType\x12\t\n\x05\x41\x44\x44\x45\x44\x10\x00\x12\x0b\n\x07REMOVED\x10\x01\x12\x0b\n\x07UPDATED\x10\x02\"w\n\nGraphEvent\x12.\n\x0cnode_changed\x18\x01 \x01(\x0b\x32\x16.rqt2.api.v1.NodeEventH\x00\x12\x30\n\rtopic_changed\x18\x02 \x01(\x0b\x32\x17.rqt2.api.v1.TopicEventH\x00\x42\x07\n\x05\x65vent2\xe5\x01\n\x14IntrospectionService\x12?\n\tListNodes\x12\x12.rqt2.api.v1.Empty\x1a\x1e.rqt2.api.v1.ListNodesResponse\x12\x41\n\nListTopics\x12\x12.rqt2.api.v1.Empty\x1a\x1f.rqt2.api.v1.ListTopicsResponse\x12I\n\nWatchGraph\x12 .rqt2.api.v1.IntrospectionFilter\x1a\x17.rqt2.api.v1.GraphEvent0\x01\x62\x06proto3')
  ,
  dependencies=[types__pb2.DESCRIPTOR,])



_NODEEVENT_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='rqt2.api.v1.NodeEvent.EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADDED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMOVED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATED', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=550,
  serialized_end=598,
)
_sym_db.RegisterEnumDescriptor(_NODEEVENT_EVENTTYPE)

_TOPICEVENT_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='rqt2.api.v1.TopicEvent.EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADDED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMOVED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATED', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=550,
  serialized_end=598,
)
_sym_db.RegisterEnumDescriptor(_TOPICEVENT_EVENTTYPE)


_INTROSPECTIONFILTER = _descriptor.Descriptor(
  name='IntrospectionFilter',
  full_name='rqt2.api.v1.IntrospectionFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespaces', full_name='rqt2.api.v1.IntrospectionFilter.namespaces', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_name_regex', full_name='rqt2.api.v1.IntrospectionFilter.node_name_regex', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=115,
)


_TOPICINFOEXTENDED = _descriptor.Descriptor(
  name='TopicInfoExtended',
  full_name='rqt2.api.v1.TopicInfoExtended',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rqt2.api.v1.TopicInfoExtended.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_type', full_name='rqt2.api.v1.TopicInfoExtended.message_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publisher_count', full_name='rqt2.api.v1.TopicInfoExtended.publisher_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subscriber_count', full_name='rqt2.api.v1.TopicInfoExtended.subscriber_count', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qos_profiles', full_name='rqt2.api.v1.TopicInfoExtended.qos_profiles', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=246,
)


_LISTNODESRESPONSE = _descriptor.Descriptor(
  name='ListNodesResponse',
  full_name='rqt2.api.v1.ListNodesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='rqt2.api.v1.ListNodesResponse.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='rqt2.api.v1.ListNodesResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=342,
)


_LISTTOPICSRESPONSE = _descriptor.Descriptor(
  name='ListTopicsResponse',
  full_name='rqt2.api.v1.ListTopicsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topics', full_name='rqt2.api.v1.ListTopicsResponse.topics', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='rqt2.api.v1.ListTopicsResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=449,
)


_NODEEVENT = _descriptor.Descriptor(
  name='NodeEvent',
  full_name='rqt2.api.v1.NodeEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='rqt2.api.v1.NodeEvent.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node', full_name='rqt2.api.v1.NodeEvent.node', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NODEEVENT_EVENTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=598,
)


_TOPICEVENT = _descriptor.Descriptor(
  name='TopicEvent',
  full_name='rqt2.api.v1.TopicEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='rqt2.api.v1.TopicEvent.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic', full_name='rqt2.api.v1.TopicEvent.topic', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TOPICEVENT_EVENTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=601,
  serialized_end=751,
)


_GRAPHEVENT = _descriptor.Descriptor(
  name='GraphEvent',
  full_name='rqt2.api.v1.GraphEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_changed', full_name='rqt2.api.v1.GraphEvent.node_changed', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic_changed', full_name='rqt2.api.v1.GraphEvent.topic_changed', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='event', full_name='rqt2.api.v1.GraphEvent.event',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=753,
  serialized_end=872,
)

_LISTNODESRESPONSE.fields_by_name['nodes'].message_type = types__pb2._NODEINFO
_LISTNODESRESPONSE.fields_by_name['status'].message_type = types__pb2._STATUS
_LISTTOPICSRESPONSE.fields_by_name['topics'].message_type = _TOPICINFOEXTENDED
_LISTTOPICSRESPONSE.fields_by_name['status'].message_type = types__pb2._STATUS
_NODEEVENT.fields_by_name['type'].enum_type = _NODEEVENT_EVENTTYPE
_NODEEVENT.fields_by_name['node'].message_type = types__pb2._NODEINFO
_NODEEVENT_EVENTTYPE.containing_type = _NODEEVENT
_TOPICEVENT.fields_by_name['type'].enum_type = _TOPICEVENT_EVENTTYPE
_TOPICEVENT.fields_by_name['topic'].message_type = types__pb2._TOPICINFO
_TOPICEVENT_EVENTTYPE.containing_type = _TOPICEVENT
_GRAPHEVENT.fields_by_name['node_changed'].message_type = _NODEEVENT
_GRAPHEVENT.fields_by_name['topic_changed'].message_type = _TOPICEVENT
_GRAPHEVENT.oneofs_by_name['event'].fields.append(
  _GRAPHEVENT.fields_by_name['node_changed'])
_GRAPHEVENT.fields_by_name['node_changed'].containing_oneof = _GRAPHEVENT.oneofs_by_name['event']
_GRAPHEVENT.oneofs_by_name['event'].fields.append(
  _GRAPHEVENT.fields_by_name['topic_changed'])
_GRAPHEVENT.fields_by_name['topic_changed'].containing_oneof = _GRAPHEVENT.oneofs_by_name['event']
DESCRIPTOR.message_types_by_name['IntrospectionFilter'] = _INTROSPECTIONFILTER
DESCRIPTOR.message_types_by_name['TopicInfoExtended'] = _TOPICINFOEXTENDED
DESCRIPTOR.message_types_by_name['ListNodesResponse'] = _LISTNODESRESPONSE
DESCRIPTOR.message_types_by_name['ListTopicsResponse'] = _LISTTOPICSRESPONSE
DESCRIPTOR.message_types_by_name['NodeEvent'] = _NODEEVENT
DESCRIPTOR.message_types_by_name['TopicEvent'] = _TOPICEVENT
DESCRIPTOR.message_types_by_name['GraphEvent'] = _GRAPHEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IntrospectionFilter = _reflection.GeneratedProtocolMessageType('IntrospectionFilter', (_message.Message,), dict(
  DESCRIPTOR = _INTROSPECTIONFILTER,
  __module__ = 'introspection_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.IntrospectionFilter)
  ))
_sym_db.RegisterMessage(IntrospectionFilter)

TopicInfoExtended = _reflection.GeneratedProtocolMessageType('TopicInfoExtended', (_message.Message,), dict(
  DESCRIPTOR = _TOPICINFOEXTENDED,
  __module__ = 'introspection_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.TopicInfoExtended)
  ))
_sym_db.RegisterMessage(TopicInfoExtended)

ListNodesResponse = _reflection.GeneratedProtocolMessageType('ListNodesResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTNODESRESPONSE,
  __module__ = 'introspection_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.ListNodesResponse)
  ))
_sym_db.RegisterMessage(ListNodesResponse)

ListTopicsResponse = _reflection.GeneratedProtocolMessageType('ListTopicsResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTTOPICSRESPONSE,
  __module__ = 'introspection_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.ListTopicsResponse)
  ))
_sym_db.RegisterMessage(ListTopicsResponse)

NodeEvent = _reflection.GeneratedProtocolMessageType('NodeEvent', (_message.Message,), dict(
  DESCRIPTOR = _NODEEVENT,
  __module__ = 'introspection_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.NodeEvent)
  ))
_sym_db.RegisterMessage(NodeEvent)

TopicEvent = _reflection.GeneratedProtocolMessageType('TopicEvent', (_message.Message,), dict(
  DESCRIPTOR = _TOPICEVENT,
  __module__ = 'introspection_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.TopicEvent)
  ))
_sym_db.RegisterMessage(TopicEvent)

GraphEvent = _reflection.GeneratedProtocolMessageType('GraphEvent', (_message.Message,), dict(
  DESCRIPTOR = _GRAPHEVENT,
  __module__ = 'introspection_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.GraphEvent)
  ))
_sym_db.RegisterMessage(GraphEvent)



_INTROSPECTIONSERVICE = _descriptor.ServiceDescriptor(
  name='IntrospectionService',
  full_name='rqt2.api.v1.IntrospectionService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=875,
  serialized_end=1104,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListNodes',
    full_name='rqt2.api.v1.IntrospectionService.ListNodes',
    index=0,
    containing_service=None,
    input_type=types__pb2._EMPTY,
    output_type=_LISTNODESRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListTopics',
    full_name='rqt2.api.v1.IntrospectionService.ListTopics',
    index=1,
    containing_service=None,
    input_type=types__pb2._EMPTY,
    output_type=_LISTTOPICSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='WatchGraph',
    full_name='rqt2.api.v1.IntrospectionService.WatchGraph',
    index=2,
    containing_service=None,
    input_type=_INTROSPECTIONFILTER,
    output_type=_GRAPHEVENT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INTROSPECTIONSERVICE)

DESCRIPTOR.services_by_name['IntrospectionService'] = _INTROSPECTIONSERVICE

# @@protoc_insertion_point(module_scope)
