# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import introspection_pb2 as introspection__pb2
import types_pb2 as types__pb2


class IntrospectionServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListNodes = channel.unary_unary(
        '/rqt2.api.v1.IntrospectionService/ListNodes',
        request_serializer=types__pb2.Empty.SerializeToString,
        response_deserializer=introspection__pb2.ListNodesResponse.FromString,
        )
    self.ListTopics = channel.unary_unary(
        '/rqt2.api.v1.IntrospectionService/ListTopics',
        request_serializer=types__pb2.Empty.SerializeToString,
        response_deserializer=introspection__pb2.ListTopicsResponse.FromString,
        )
    self.WatchGraph = channel.unary_stream(
        '/rqt2.api.v1.IntrospectionService/WatchGraph',
        request_serializer=introspection__pb2.IntrospectionFilter.SerializeToString,
        response_deserializer=introspection__pb2.GraphEvent.FromString,
        )


class IntrospectionServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListNodes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListTopics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WatchGraph(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IntrospectionServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListNodes': grpc.unary_unary_rpc_method_handler(
          servicer.ListNodes,
          request_deserializer=types__pb2.Empty.FromString,
          response_serializer=introspection__pb2.ListNodesResponse.SerializeToString,
      ),
      'ListTopics': grpc.unary_unary_rpc_method_handler(
          servicer.ListTopics,
          request_deserializer=types__pb2.Empty.FromString,
          response_serializer=introspection__pb2.ListTopicsResponse.SerializeToString,
      ),
      'WatchGraph': grpc.unary_stream_rpc_method_handler(
          servicer.WatchGraph,
          request_deserializer=introspection__pb2.IntrospectionFilter.FromString,
          response_serializer=introspection__pb2.GraphEvent.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rqt2.api.v1.IntrospectionService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
