# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: security.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='security.proto',
  package='rqt2.api.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x0esecurity.proto\x12\x0brqt2.api.v1\x1a\x0btypes.proto\"1\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x92\x01\n\x0c\x41uthResponse\x12\x15\n\rauthenticated\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\x12#\n\x04role\x18\x03 \x01(\x0e\x32\x15.rqt2.api.v1.UserRole\x12\x12\n\nsession_id\x18\x04 \x01(\t\x12#\n\x06status\x18\x05 \x01(\x0b\x32\x13.rqt2.api.v1.Status\"\x1a\n\x0b\x43\x65rtRequest\x12\x0b\n\x03\x63sr\x18\x01 \x01(\t\"T\n\x0c\x43\x65rtResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x17\n\x0f\x63\x65rtificate_pem\x18\x02 \x01(\t\x12\x0e\n\x06\x63\x61_pem\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t*=\n\x08UserRole\x12\t\n\x05GUEST\x10\x00\x12\x0c\n\x08OPERATOR\x10\x01\x12\r\n\tDEVELOPER\x10\x02\x12\t\n\x05\x41\x44MIN\x10\x03\x32\xa5\x01\n\x0fSecurityService\x12\x43\n\x0c\x41uthenticate\x12\x18.rqt2.api.v1.AuthRequest\x1a\x19.rqt2.api.v1.AuthResponse\x12M\n\x16RequestNodeCertificate\x12\x18.rqt2.api.v1.CertRequest\x1a\x19.rqt2.api.v1.CertResponseb\x06proto3')
  ,
  dependencies=[types__pb2.DESCRIPTOR,])

_USERROLE = _descriptor.EnumDescriptor(
  name='UserRole',
  full_name='rqt2.api.v1.UserRole',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GUEST', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPERATOR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEVELOPER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADMIN', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=358,
  serialized_end=419,
)
_sym_db.RegisterEnumDescriptor(_USERROLE)

UserRole = enum_type_wrapper.EnumTypeWrapper(_USERROLE)
GUEST = 0
OPERATOR = 1
DEVELOPER = 2
ADMIN = 3



_AUTHREQUEST = _descriptor.Descriptor(
  name='AuthRequest',
  full_name='rqt2.api.v1.AuthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='rqt2.api.v1.AuthRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='rqt2.api.v1.AuthRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=93,
)


_AUTHRESPONSE = _descriptor.Descriptor(
  name='AuthResponse',
  full_name='rqt2.api.v1.AuthResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='authenticated', full_name='rqt2.api.v1.AuthResponse.authenticated', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='rqt2.api.v1.AuthResponse.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role', full_name='rqt2.api.v1.AuthResponse.role', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_id', full_name='rqt2.api.v1.AuthResponse.session_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='rqt2.api.v1.AuthResponse.status', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=242,
)


_CERTREQUEST = _descriptor.Descriptor(
  name='CertRequest',
  full_name='rqt2.api.v1.CertRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='csr', full_name='rqt2.api.v1.CertRequest.csr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=270,
)


_CERTRESPONSE = _descriptor.Descriptor(
  name='CertResponse',
  full_name='rqt2.api.v1.CertResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='rqt2.api.v1.CertResponse.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='certificate_pem', full_name='rqt2.api.v1.CertResponse.certificate_pem', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ca_pem', full_name='rqt2.api.v1.CertResponse.ca_pem', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='rqt2.api.v1.CertResponse.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=356,
)

_AUTHRESPONSE.fields_by_name['role'].enum_type = _USERROLE
_AUTHRESPONSE.fields_by_name['status'].message_type = types__pb2._STATUS
DESCRIPTOR.message_types_by_name['AuthRequest'] = _AUTHREQUEST
DESCRIPTOR.message_types_by_name['AuthResponse'] = _AUTHRESPONSE
DESCRIPTOR.message_types_by_name['CertRequest'] = _CERTREQUEST
DESCRIPTOR.message_types_by_name['CertResponse'] = _CERTRESPONSE
DESCRIPTOR.enum_types_by_name['UserRole'] = _USERROLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthRequest = _reflection.GeneratedProtocolMessageType('AuthRequest', (_message.Message,), dict(
  DESCRIPTOR = _AUTHREQUEST,
  __module__ = 'security_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.AuthRequest)
  ))
_sym_db.RegisterMessage(AuthRequest)

AuthResponse = _reflection.GeneratedProtocolMessageType('AuthResponse', (_message.Message,), dict(
  DESCRIPTOR = _AUTHRESPONSE,
  __module__ = 'security_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.AuthResponse)
  ))
_sym_db.RegisterMessage(AuthResponse)

CertRequest = _reflection.GeneratedProtocolMessageType('CertRequest', (_message.Message,), dict(
  DESCRIPTOR = _CERTREQUEST,
  __module__ = 'security_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.CertRequest)
  ))
_sym_db.RegisterMessage(CertRequest)

CertResponse = _reflection.GeneratedProtocolMessageType('CertResponse', (_message.Message,), dict(
  DESCRIPTOR = _CERTRESPONSE,
  __module__ = 'security_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.CertResponse)
  ))
_sym_db.RegisterMessage(CertResponse)



_SECURITYSERVICE = _descriptor.ServiceDescriptor(
  name='SecurityService',
  full_name='rqt2.api.v1.SecurityService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=422,
  serialized_end=587,
  methods=[
  _descriptor.MethodDescriptor(
    name='Authenticate',
    full_name='rqt2.api.v1.SecurityService.Authenticate',
    index=0,
    containing_service=None,
    input_type=_AUTHREQUEST,
    output_type=_AUTHRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RequestNodeCertificate',
    full_name='rqt2.api.v1.SecurityService.RequestNodeCertificate',
    index=1,
    containing_service=None,
    input_type=_CERTREQUEST,
    output_type=_CERTRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SECURITYSERVICE)

DESCRIPTOR.services_by_name['SecurityService'] = _SECURITYSERVICE

# @@protoc_insertion_point(module_scope)
