# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import security_pb2 as security__pb2


class SecurityServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Authenticate = channel.unary_unary(
        '/rqt2.api.v1.SecurityService/Authenticate',
        request_serializer=security__pb2.AuthRequest.SerializeToString,
        response_deserializer=security__pb2.AuthResponse.FromString,
        )
    self.RequestNodeCertificate = channel.unary_unary(
        '/rqt2.api.v1.SecurityService/RequestNodeCertificate',
        request_serializer=security__pb2.CertRequest.SerializeToString,
        response_deserializer=security__pb2.CertResponse.FromString,
        )


class SecurityServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Authenticate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestNodeCertificate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SecurityServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Authenticate': grpc.unary_unary_rpc_method_handler(
          servicer.Authenticate,
          request_deserializer=security__pb2.AuthRequest.FromString,
          response_serializer=security__pb2.AuthResponse.SerializeToString,
      ),
      'RequestNodeCertificate': grpc.unary_unary_rpc_method_handler(
          servicer.RequestNodeCertificate,
          request_deserializer=security__pb2.CertRequest.FromString,
          response_serializer=security__pb2.CertResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rqt2.api.v1.SecurityService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
