# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: settings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='settings.proto',
  package='rqt2.api.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x0esettings.proto\x12\x0brqt2.api.v1\x1a\x0btypes.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"%\n\x07Setting\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"0\n\x12GetSettingsRequest\x12\r\n\x05scope\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"]\n\x0fSettingResponse\x12%\n\x07setting\x18\x01 \x01(\x0b\x32\x14.rqt2.api.v1.Setting\x12#\n\x06status\x18\x02 \x01(\x0b\x32\x13.rqt2.api.v1.Status\"J\n\x12SetSettingsRequest\x12\r\n\x05scope\x18\x01 \x01(\t\x12%\n\x07setting\x18\x02 \x01(\x0b\x32\x14.rqt2.api.v1.Setting\"$\n\x13ListSettingsRequest\x12\r\n\x05scope\x18\x01 \x01(\t\"c\n\x14ListSettingsResponse\x12&\n\x08settings\x18\x01 \x03(\x0b\x32\x14.rqt2.api.v1.Setting\x12#\n\x06status\x18\x02 \x01(\x0b\x32\x13.rqt2.api.v1.Status\"%\n\x14WatchSettingsRequest\x12\r\n\x05scope\x18\x01 \x01(\t\"\x91\x01\n\x0cSettingEvent\x12,\n\x04type\x18\x01 \x01(\x0e\x32\x1e.rqt2.api.v1.SettingEvent.Type\x12%\n\x07setting\x18\x02 \x01(\x0b\x32\x14.rqt2.api.v1.Setting\",\n\x04Type\x12\t\n\x05\x41\x44\x44\x45\x44\x10\x00\x12\x0c\n\x08MODIFIED\x10\x01\x12\x0b\n\x07REMOVED\x10\x02\x32\xaa\x02\n\x0fSettingsService\x12\x44\n\x03Get\x12\x1f.rqt2.api.v1.GetSettingsRequest\x1a\x1c.rqt2.api.v1.SettingResponse\x12;\n\x03Set\x12\x1f.rqt2.api.v1.SetSettingsRequest\x1a\x13.rqt2.api.v1.Status\x12K\n\x04List\x12 .rqt2.api.v1.ListSettingsRequest\x1a!.rqt2.api.v1.ListSettingsResponse\x12G\n\x05Watch\x12!.rqt2.api.v1.WatchSettingsRequest\x1a\x19.rqt2.api.v1.SettingEvent0\x01\x62\x06proto3')
  ,
  dependencies=[types__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])



_SETTINGEVENT_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='rqt2.api.v1.SettingEvent.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADDED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MODIFIED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMOVED', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=617,
  serialized_end=661,
)
_sym_db.RegisterEnumDescriptor(_SETTINGEVENT_TYPE)


_SETTING = _descriptor.Descriptor(
  name='Setting',
  full_name='rqt2.api.v1.Setting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='rqt2.api.v1.Setting.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='rqt2.api.v1.Setting.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=114,
)


_GETSETTINGSREQUEST = _descriptor.Descriptor(
  name='GetSettingsRequest',
  full_name='rqt2.api.v1.GetSettingsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scope', full_name='rqt2.api.v1.GetSettingsRequest.scope', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='rqt2.api.v1.GetSettingsRequest.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=164,
)


_SETTINGRESPONSE = _descriptor.Descriptor(
  name='SettingResponse',
  full_name='rqt2.api.v1.SettingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='setting', full_name='rqt2.api.v1.SettingResponse.setting', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='rqt2.api.v1.SettingResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=259,
)


_SETSETTINGSREQUEST = _descriptor.Descriptor(
  name='SetSettingsRequest',
  full_name='rqt2.api.v1.SetSettingsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scope', full_name='rqt2.api.v1.SetSettingsRequest.scope', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='setting', full_name='rqt2.api.v1.SetSettingsRequest.setting', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=335,
)


_LISTSETTINGSREQUEST = _descriptor.Descriptor(
  name='ListSettingsRequest',
  full_name='rqt2.api.v1.ListSettingsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scope', full_name='rqt2.api.v1.ListSettingsRequest.scope', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=373,
)


_LISTSETTINGSRESPONSE = _descriptor.Descriptor(
  name='ListSettingsResponse',
  full_name='rqt2.api.v1.ListSettingsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='settings', full_name='rqt2.api.v1.ListSettingsResponse.settings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='rqt2.api.v1.ListSettingsResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=474,
)


_WATCHSETTINGSREQUEST = _descriptor.Descriptor(
  name='WatchSettingsRequest',
  full_name='rqt2.api.v1.WatchSettingsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scope', full_name='rqt2.api.v1.WatchSettingsRequest.scope', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=476,
  serialized_end=513,
)


_SETTINGEVENT = _descriptor.Descriptor(
  name='SettingEvent',
  full_name='rqt2.api.v1.SettingEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='rqt2.api.v1.SettingEvent.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='setting', full_name='rqt2.api.v1.SettingEvent.setting', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SETTINGEVENT_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=516,
  serialized_end=661,
)

_SETTINGRESPONSE.fields_by_name['setting'].message_type = _SETTING
_SETTINGRESPONSE.fields_by_name['status'].message_type = types__pb2._STATUS
_SETSETTINGSREQUEST.fields_by_name['setting'].message_type = _SETTING
_LISTSETTINGSRESPONSE.fields_by_name['settings'].message_type = _SETTING
_LISTSETTINGSRESPONSE.fields_by_name['status'].message_type = types__pb2._STATUS
_SETTINGEVENT.fields_by_name['type'].enum_type = _SETTINGEVENT_TYPE
_SETTINGEVENT.fields_by_name['setting'].message_type = _SETTING
_SETTINGEVENT_TYPE.containing_type = _SETTINGEVENT
DESCRIPTOR.message_types_by_name['Setting'] = _SETTING
DESCRIPTOR.message_types_by_name['GetSettingsRequest'] = _GETSETTINGSREQUEST
DESCRIPTOR.message_types_by_name['SettingResponse'] = _SETTINGRESPONSE
DESCRIPTOR.message_types_by_name['SetSettingsRequest'] = _SETSETTINGSREQUEST
DESCRIPTOR.message_types_by_name['ListSettingsRequest'] = _LISTSETTINGSREQUEST
DESCRIPTOR.message_types_by_name['ListSettingsResponse'] = _LISTSETTINGSRESPONSE
DESCRIPTOR.message_types_by_name['WatchSettingsRequest'] = _WATCHSETTINGSREQUEST
DESCRIPTOR.message_types_by_name['SettingEvent'] = _SETTINGEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Setting = _reflection.GeneratedProtocolMessageType('Setting', (_message.Message,), dict(
  DESCRIPTOR = _SETTING,
  __module__ = 'settings_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.Setting)
  ))
_sym_db.RegisterMessage(Setting)

GetSettingsRequest = _reflection.GeneratedProtocolMessageType('GetSettingsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETSETTINGSREQUEST,
  __module__ = 'settings_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.GetSettingsRequest)
  ))
_sym_db.RegisterMessage(GetSettingsRequest)

SettingResponse = _reflection.GeneratedProtocolMessageType('SettingResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETTINGRESPONSE,
  __module__ = 'settings_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.SettingResponse)
  ))
_sym_db.RegisterMessage(SettingResponse)

SetSettingsRequest = _reflection.GeneratedProtocolMessageType('SetSettingsRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETSETTINGSREQUEST,
  __module__ = 'settings_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.SetSettingsRequest)
  ))
_sym_db.RegisterMessage(SetSettingsRequest)

ListSettingsRequest = _reflection.GeneratedProtocolMessageType('ListSettingsRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTSETTINGSREQUEST,
  __module__ = 'settings_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.ListSettingsRequest)
  ))
_sym_db.RegisterMessage(ListSettingsRequest)

ListSettingsResponse = _reflection.GeneratedProtocolMessageType('ListSettingsResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTSETTINGSRESPONSE,
  __module__ = 'settings_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.ListSettingsResponse)
  ))
_sym_db.RegisterMessage(ListSettingsResponse)

WatchSettingsRequest = _reflection.GeneratedProtocolMessageType('WatchSettingsRequest', (_message.Message,), dict(
  DESCRIPTOR = _WATCHSETTINGSREQUEST,
  __module__ = 'settings_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.WatchSettingsRequest)
  ))
_sym_db.RegisterMessage(WatchSettingsRequest)

SettingEvent = _reflection.GeneratedProtocolMessageType('SettingEvent', (_message.Message,), dict(
  DESCRIPTOR = _SETTINGEVENT,
  __module__ = 'settings_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.SettingEvent)
  ))
_sym_db.RegisterMessage(SettingEvent)



_SETTINGSSERVICE = _descriptor.ServiceDescriptor(
  name='SettingsService',
  full_name='rqt2.api.v1.SettingsService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=664,
  serialized_end=962,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='rqt2.api.v1.SettingsService.Get',
    index=0,
    containing_service=None,
    input_type=_GETSETTINGSREQUEST,
    output_type=_SETTINGRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Set',
    full_name='rqt2.api.v1.SettingsService.Set',
    index=1,
    containing_service=None,
    input_type=_SETSETTINGSREQUEST,
    output_type=types__pb2._STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='List',
    full_name='rqt2.api.v1.SettingsService.List',
    index=2,
    containing_service=None,
    input_type=_LISTSETTINGSREQUEST,
    output_type=_LISTSETTINGSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Watch',
    full_name='rqt2.api.v1.SettingsService.Watch',
    index=3,
    containing_service=None,
    input_type=_WATCHSETTINGSREQUEST,
    output_type=_SETTINGEVENT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SETTINGSSERVICE)

DESCRIPTOR.services_by_name['SettingsService'] = _SETTINGSSERVICE

# @@protoc_insertion_point(module_scope)
