# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import settings_pb2 as settings__pb2
import types_pb2 as types__pb2


class SettingsServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Get = channel.unary_unary(
        '/rqt2.api.v1.SettingsService/Get',
        request_serializer=settings__pb2.GetSettingsRequest.SerializeToString,
        response_deserializer=settings__pb2.SettingResponse.FromString,
        )
    self.Set = channel.unary_unary(
        '/rqt2.api.v1.SettingsService/Set',
        request_serializer=settings__pb2.SetSettingsRequest.SerializeToString,
        response_deserializer=types__pb2.Status.FromString,
        )
    self.List = channel.unary_unary(
        '/rqt2.api.v1.SettingsService/List',
        request_serializer=settings__pb2.ListSettingsRequest.SerializeToString,
        response_deserializer=settings__pb2.ListSettingsResponse.FromString,
        )
    self.Watch = channel.unary_stream(
        '/rqt2.api.v1.SettingsService/Watch',
        request_serializer=settings__pb2.WatchSettingsRequest.SerializeToString,
        response_deserializer=settings__pb2.SettingEvent.FromString,
        )


class SettingsServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Set(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Watch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SettingsServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=settings__pb2.GetSettingsRequest.FromString,
          response_serializer=settings__pb2.SettingResponse.SerializeToString,
      ),
      'Set': grpc.unary_unary_rpc_method_handler(
          servicer.Set,
          request_deserializer=settings__pb2.SetSettingsRequest.FromString,
          response_serializer=types__pb2.Status.SerializeToString,
      ),
      'List': grpc.unary_unary_rpc_method_handler(
          servicer.List,
          request_deserializer=settings__pb2.ListSettingsRequest.FromString,
          response_serializer=settings__pb2.ListSettingsResponse.SerializeToString,
      ),
      'Watch': grpc.unary_stream_rpc_method_handler(
          servicer.Watch,
          request_deserializer=settings__pb2.WatchSettingsRequest.FromString,
          response_serializer=settings__pb2.SettingEvent.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rqt2.api.v1.SettingsService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
