# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import system_utils_pb2 as system__utils__pb2
import types_pb2 as types__pb2


class SystemUtilsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RestartDaemon = channel.unary_unary(
        '/rqt2.api.v1.SystemUtils/RestartDaemon',
        request_serializer=types__pb2.Empty.SerializeToString,
        response_deserializer=types__pb2.Status.FromString,
        )
    self.RunCommand = channel.unary_stream(
        '/rqt2.api.v1.SystemUtils/RunCommand',
        request_serializer=system__utils__pb2.CommandRequest.SerializeToString,
        response_deserializer=system__utils__pb2.CommandOutput.FromString,
        )
    self.StartSSHSession = channel.unary_unary(
        '/rqt2.api.v1.SystemUtils/StartSSHSession',
        request_serializer=system__utils__pb2.SSHConfig.SerializeToString,
        response_deserializer=system__utils__pb2.SSHSession.FromString,
        )
    self.ExecRemote = channel.unary_stream(
        '/rqt2.api.v1.SystemUtils/ExecRemote',
        request_serializer=system__utils__pb2.RemoteExecRequest.SerializeToString,
        response_deserializer=system__utils__pb2.CommandOutput.FromString,
        )


class SystemUtilsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RestartDaemon(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RunCommand(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartSSHSession(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExecRemote(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SystemUtilsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RestartDaemon': grpc.unary_unary_rpc_method_handler(
          servicer.RestartDaemon,
          request_deserializer=types__pb2.Empty.FromString,
          response_serializer=types__pb2.Status.SerializeToString,
      ),
      'RunCommand': grpc.unary_stream_rpc_method_handler(
          servicer.RunCommand,
          request_deserializer=system__utils__pb2.CommandRequest.FromString,
          response_serializer=system__utils__pb2.CommandOutput.SerializeToString,
      ),
      'StartSSHSession': grpc.unary_unary_rpc_method_handler(
          servicer.StartSSHSession,
          request_deserializer=system__utils__pb2.SSHConfig.FromString,
          response_serializer=system__utils__pb2.SSHSession.SerializeToString,
      ),
      'ExecRemote': grpc.unary_stream_rpc_method_handler(
          servicer.ExecRemote,
          request_deserializer=system__utils__pb2.RemoteExecRequest.FromString,
          response_serializer=system__utils__pb2.CommandOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rqt2.api.v1.SystemUtils', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
