# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system_utils.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='system_utils.proto',
  package='rqt2.api.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x12system_utils.proto\x12\x0brqt2.api.v1\x1a\x0btypes.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x01\n\x0e\x43ommandRequest\x12\x12\n\nexecutable\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\x12\x31\n\x03\x65nv\x18\x03 \x03(\x0b\x32$.rqt2.api.v1.CommandRequest.EnvEntry\x12\x13\n\x0bworking_dir\x18\x04 \x01(\t\x12\x11\n\tsudowoodo\x18\x05 \x01(\x08\x1a*\n\x08\x45nvEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"u\n\rCommandOutput\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x06stream\x18\x02 \x01(\x0e\x32\x17.rqt2.api.v1.StreamType\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"x\n\tSSHConfig\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x0c\n\x04user\x18\x03 \x01(\t\x12\x12\n\x08password\x18\x04 \x01(\tH\x00\x12\x12\n\x08key_path\x18\x05 \x01(\tH\x00\x12\x11\n\ttimeout_s\x18\x06 \x01(\x05\x42\x06\n\x04\x61uth\"a\n\nSSHSession\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t\x12#\n\x06status\x18\x04 \x01(\x0b\x32\x13.rqt2.api.v1.Status\"F\n\x11RemoteExecRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x03(\t*$\n\nStreamType\x12\n\n\x06STDOUT\x10\x00\x12\n\n\x06STDERR\x10\x01\x32\xa0\x02\n\x0bSystemUtils\x12\x38\n\rRestartDaemon\x12\x12.rqt2.api.v1.Empty\x1a\x13.rqt2.api.v1.Status\x12G\n\nRunCommand\x12\x1b.rqt2.api.v1.CommandRequest\x1a\x1a.rqt2.api.v1.CommandOutput0\x01\x12\x42\n\x0fStartSSHSession\x12\x16.rqt2.api.v1.SSHConfig\x1a\x17.rqt2.api.v1.SSHSession\x12J\n\nExecRemote\x12\x1e.rqt2.api.v1.RemoteExecRequest\x1a\x1a.rqt2.api.v1.CommandOutput0\x01\x62\x06proto3')
  ,
  dependencies=[types__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_STREAMTYPE = _descriptor.EnumDescriptor(
  name='StreamType',
  full_name='rqt2.api.v1.StreamType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STDOUT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STDERR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=681,
  serialized_end=717,
)
_sym_db.RegisterEnumDescriptor(_STREAMTYPE)

StreamType = enum_type_wrapper.EnumTypeWrapper(_STREAMTYPE)
STDOUT = 0
STDERR = 1



_COMMANDREQUEST_ENVENTRY = _descriptor.Descriptor(
  name='EnvEntry',
  full_name='rqt2.api.v1.CommandRequest.EnvEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='rqt2.api.v1.CommandRequest.EnvEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='rqt2.api.v1.CommandRequest.EnvEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=267,
)

_COMMANDREQUEST = _descriptor.Descriptor(
  name='CommandRequest',
  full_name='rqt2.api.v1.CommandRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='executable', full_name='rqt2.api.v1.CommandRequest.executable', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='rqt2.api.v1.CommandRequest.args', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='env', full_name='rqt2.api.v1.CommandRequest.env', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='working_dir', full_name='rqt2.api.v1.CommandRequest.working_dir', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sudowoodo', full_name='rqt2.api.v1.CommandRequest.sudowoodo', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_COMMANDREQUEST_ENVENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=267,
)


_COMMANDOUTPUT = _descriptor.Descriptor(
  name='CommandOutput',
  full_name='rqt2.api.v1.CommandOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='rqt2.api.v1.CommandOutput.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stream', full_name='rqt2.api.v1.CommandOutput.stream', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='rqt2.api.v1.CommandOutput.data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=386,
)


_SSHCONFIG = _descriptor.Descriptor(
  name='SSHConfig',
  full_name='rqt2.api.v1.SSHConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='rqt2.api.v1.SSHConfig.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='rqt2.api.v1.SSHConfig.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='rqt2.api.v1.SSHConfig.user', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='rqt2.api.v1.SSHConfig.password', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_path', full_name='rqt2.api.v1.SSHConfig.key_path', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout_s', full_name='rqt2.api.v1.SSHConfig.timeout_s', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='auth', full_name='rqt2.api.v1.SSHConfig.auth',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=388,
  serialized_end=508,
)


_SSHSESSION = _descriptor.Descriptor(
  name='SSHSession',
  full_name='rqt2.api.v1.SSHSession',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='rqt2.api.v1.SSHSession.session_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='rqt2.api.v1.SSHSession.host', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='rqt2.api.v1.SSHSession.user', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='rqt2.api.v1.SSHSession.status', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=510,
  serialized_end=607,
)


_REMOTEEXECREQUEST = _descriptor.Descriptor(
  name='RemoteExecRequest',
  full_name='rqt2.api.v1.RemoteExecRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='rqt2.api.v1.RemoteExecRequest.session_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='rqt2.api.v1.RemoteExecRequest.command', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='rqt2.api.v1.RemoteExecRequest.args', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=609,
  serialized_end=679,
)

_COMMANDREQUEST_ENVENTRY.containing_type = _COMMANDREQUEST
_COMMANDREQUEST.fields_by_name['env'].message_type = _COMMANDREQUEST_ENVENTRY
_COMMANDOUTPUT.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_COMMANDOUTPUT.fields_by_name['stream'].enum_type = _STREAMTYPE
_SSHCONFIG.oneofs_by_name['auth'].fields.append(
  _SSHCONFIG.fields_by_name['password'])
_SSHCONFIG.fields_by_name['password'].containing_oneof = _SSHCONFIG.oneofs_by_name['auth']
_SSHCONFIG.oneofs_by_name['auth'].fields.append(
  _SSHCONFIG.fields_by_name['key_path'])
_SSHCONFIG.fields_by_name['key_path'].containing_oneof = _SSHCONFIG.oneofs_by_name['auth']
_SSHSESSION.fields_by_name['status'].message_type = types__pb2._STATUS
DESCRIPTOR.message_types_by_name['CommandRequest'] = _COMMANDREQUEST
DESCRIPTOR.message_types_by_name['CommandOutput'] = _COMMANDOUTPUT
DESCRIPTOR.message_types_by_name['SSHConfig'] = _SSHCONFIG
DESCRIPTOR.message_types_by_name['SSHSession'] = _SSHSESSION
DESCRIPTOR.message_types_by_name['RemoteExecRequest'] = _REMOTEEXECREQUEST
DESCRIPTOR.enum_types_by_name['StreamType'] = _STREAMTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommandRequest = _reflection.GeneratedProtocolMessageType('CommandRequest', (_message.Message,), dict(

  EnvEntry = _reflection.GeneratedProtocolMessageType('EnvEntry', (_message.Message,), dict(
    DESCRIPTOR = _COMMANDREQUEST_ENVENTRY,
    __module__ = 'system_utils_pb2'
    # @@protoc_insertion_point(class_scope:rqt2.api.v1.CommandRequest.EnvEntry)
    ))
  ,
  DESCRIPTOR = _COMMANDREQUEST,
  __module__ = 'system_utils_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.CommandRequest)
  ))
_sym_db.RegisterMessage(CommandRequest)
_sym_db.RegisterMessage(CommandRequest.EnvEntry)

CommandOutput = _reflection.GeneratedProtocolMessageType('CommandOutput', (_message.Message,), dict(
  DESCRIPTOR = _COMMANDOUTPUT,
  __module__ = 'system_utils_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.CommandOutput)
  ))
_sym_db.RegisterMessage(CommandOutput)

SSHConfig = _reflection.GeneratedProtocolMessageType('SSHConfig', (_message.Message,), dict(
  DESCRIPTOR = _SSHCONFIG,
  __module__ = 'system_utils_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.SSHConfig)
  ))
_sym_db.RegisterMessage(SSHConfig)

SSHSession = _reflection.GeneratedProtocolMessageType('SSHSession', (_message.Message,), dict(
  DESCRIPTOR = _SSHSESSION,
  __module__ = 'system_utils_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.SSHSession)
  ))
_sym_db.RegisterMessage(SSHSession)

RemoteExecRequest = _reflection.GeneratedProtocolMessageType('RemoteExecRequest', (_message.Message,), dict(
  DESCRIPTOR = _REMOTEEXECREQUEST,
  __module__ = 'system_utils_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.RemoteExecRequest)
  ))
_sym_db.RegisterMessage(RemoteExecRequest)


_COMMANDREQUEST_ENVENTRY.has_options = True
_COMMANDREQUEST_ENVENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_SYSTEMUTILS = _descriptor.ServiceDescriptor(
  name='SystemUtils',
  full_name='rqt2.api.v1.SystemUtils',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=720,
  serialized_end=1008,
  methods=[
  _descriptor.MethodDescriptor(
    name='RestartDaemon',
    full_name='rqt2.api.v1.SystemUtils.RestartDaemon',
    index=0,
    containing_service=None,
    input_type=types__pb2._EMPTY,
    output_type=types__pb2._STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RunCommand',
    full_name='rqt2.api.v1.SystemUtils.RunCommand',
    index=1,
    containing_service=None,
    input_type=_COMMANDREQUEST,
    output_type=_COMMANDOUTPUT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StartSSHSession',
    full_name='rqt2.api.v1.SystemUtils.StartSSHSession',
    index=2,
    containing_service=None,
    input_type=_SSHCONFIG,
    output_type=_SSHSESSION,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ExecRemote',
    full_name='rqt2.api.v1.SystemUtils.ExecRemote',
    index=3,
    containing_service=None,
    input_type=_REMOTEEXECREQUEST,
    output_type=_COMMANDOUTPUT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SYSTEMUTILS)

DESCRIPTOR.services_by_name['SystemUtils'] = _SYSTEMUTILS

# @@protoc_insertion_point(module_scope)
