# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: terminal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='terminal.proto',
  package='rqt2.api.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x0eterminal.proto\x12\x0brqt2.api.v1\x1a\x0btypes.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x01\n\x14StartTerminalRequest\x12\x0c\n\x04\x63ols\x18\x01 \x01(\x05\x12\x0c\n\x04rows\x18\x02 \x01(\x05\x12\x0b\n\x03\x63wd\x18\x03 \x01(\t\x12\x37\n\x03\x65nv\x18\x04 \x03(\x0b\x32*.rqt2.api.v1.StartTerminalRequest.EnvEntry\x1a*\n\x08\x45nvEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"P\n\x15StartTerminalResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12#\n\x06status\x18\x02 \x01(\x0b\x32\x13.rqt2.api.v1.Status\"#\n\rAttachRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"a\n\x0eTerminalOutput\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"1\n\rTerminalInput\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"@\n\x0eTerminalResize\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04\x63ols\x18\x02 \x01(\x05\x12\x0c\n\x04rows\x18\x03 \x01(\x05\"$\n\x0eSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t2\xdb\x02\n\x0fTerminalService\x12N\n\x05Start\x12!.rqt2.api.v1.StartTerminalRequest\x1a\".rqt2.api.v1.StartTerminalResponse\x12\x43\n\x06\x41ttach\x12\x1a.rqt2.api.v1.AttachRequest\x1a\x1b.rqt2.api.v1.TerminalOutput0\x01\x12<\n\tSendInput\x12\x1a.rqt2.api.v1.TerminalInput\x1a\x13.rqt2.api.v1.Status\x12:\n\x06Resize\x12\x1b.rqt2.api.v1.TerminalResize\x1a\x13.rqt2.api.v1.Status\x12\x39\n\x05\x43lose\x12\x1b.rqt2.api.v1.SessionRequest\x1a\x13.rqt2.api.v1.Statusb\x06proto3')
  ,
  dependencies=[types__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_STARTTERMINALREQUEST_ENVENTRY = _descriptor.Descriptor(
  name='EnvEntry',
  full_name='rqt2.api.v1.StartTerminalRequest.EnvEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='rqt2.api.v1.StartTerminalRequest.EnvEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='rqt2.api.v1.StartTerminalRequest.EnvEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=242,
)

_STARTTERMINALREQUEST = _descriptor.Descriptor(
  name='StartTerminalRequest',
  full_name='rqt2.api.v1.StartTerminalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cols', full_name='rqt2.api.v1.StartTerminalRequest.cols', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rows', full_name='rqt2.api.v1.StartTerminalRequest.rows', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cwd', full_name='rqt2.api.v1.StartTerminalRequest.cwd', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='env', full_name='rqt2.api.v1.StartTerminalRequest.env', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STARTTERMINALREQUEST_ENVENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=242,
)


_STARTTERMINALRESPONSE = _descriptor.Descriptor(
  name='StartTerminalResponse',
  full_name='rqt2.api.v1.StartTerminalResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='rqt2.api.v1.StartTerminalResponse.session_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='rqt2.api.v1.StartTerminalResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=324,
)


_ATTACHREQUEST = _descriptor.Descriptor(
  name='AttachRequest',
  full_name='rqt2.api.v1.AttachRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='rqt2.api.v1.AttachRequest.session_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=361,
)


_TERMINALOUTPUT = _descriptor.Descriptor(
  name='TerminalOutput',
  full_name='rqt2.api.v1.TerminalOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='rqt2.api.v1.TerminalOutput.session_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='rqt2.api.v1.TerminalOutput.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='rqt2.api.v1.TerminalOutput.timestamp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=460,
)


_TERMINALINPUT = _descriptor.Descriptor(
  name='TerminalInput',
  full_name='rqt2.api.v1.TerminalInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='rqt2.api.v1.TerminalInput.session_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='rqt2.api.v1.TerminalInput.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=511,
)


_TERMINALRESIZE = _descriptor.Descriptor(
  name='TerminalResize',
  full_name='rqt2.api.v1.TerminalResize',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='rqt2.api.v1.TerminalResize.session_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cols', full_name='rqt2.api.v1.TerminalResize.cols', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rows', full_name='rqt2.api.v1.TerminalResize.rows', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=513,
  serialized_end=577,
)


_SESSIONREQUEST = _descriptor.Descriptor(
  name='SessionRequest',
  full_name='rqt2.api.v1.SessionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='rqt2.api.v1.SessionRequest.session_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=579,
  serialized_end=615,
)

_STARTTERMINALREQUEST_ENVENTRY.containing_type = _STARTTERMINALREQUEST
_STARTTERMINALREQUEST.fields_by_name['env'].message_type = _STARTTERMINALREQUEST_ENVENTRY
_STARTTERMINALRESPONSE.fields_by_name['status'].message_type = types__pb2._STATUS
_TERMINALOUTPUT.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['StartTerminalRequest'] = _STARTTERMINALREQUEST
DESCRIPTOR.message_types_by_name['StartTerminalResponse'] = _STARTTERMINALRESPONSE
DESCRIPTOR.message_types_by_name['AttachRequest'] = _ATTACHREQUEST
DESCRIPTOR.message_types_by_name['TerminalOutput'] = _TERMINALOUTPUT
DESCRIPTOR.message_types_by_name['TerminalInput'] = _TERMINALINPUT
DESCRIPTOR.message_types_by_name['TerminalResize'] = _TERMINALRESIZE
DESCRIPTOR.message_types_by_name['SessionRequest'] = _SESSIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartTerminalRequest = _reflection.GeneratedProtocolMessageType('StartTerminalRequest', (_message.Message,), dict(

  EnvEntry = _reflection.GeneratedProtocolMessageType('EnvEntry', (_message.Message,), dict(
    DESCRIPTOR = _STARTTERMINALREQUEST_ENVENTRY,
    __module__ = 'terminal_pb2'
    # @@protoc_insertion_point(class_scope:rqt2.api.v1.StartTerminalRequest.EnvEntry)
    ))
  ,
  DESCRIPTOR = _STARTTERMINALREQUEST,
  __module__ = 'terminal_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.StartTerminalRequest)
  ))
_sym_db.RegisterMessage(StartTerminalRequest)
_sym_db.RegisterMessage(StartTerminalRequest.EnvEntry)

StartTerminalResponse = _reflection.GeneratedProtocolMessageType('StartTerminalResponse', (_message.Message,), dict(
  DESCRIPTOR = _STARTTERMINALRESPONSE,
  __module__ = 'terminal_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.StartTerminalResponse)
  ))
_sym_db.RegisterMessage(StartTerminalResponse)

AttachRequest = _reflection.GeneratedProtocolMessageType('AttachRequest', (_message.Message,), dict(
  DESCRIPTOR = _ATTACHREQUEST,
  __module__ = 'terminal_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.AttachRequest)
  ))
_sym_db.RegisterMessage(AttachRequest)

TerminalOutput = _reflection.GeneratedProtocolMessageType('TerminalOutput', (_message.Message,), dict(
  DESCRIPTOR = _TERMINALOUTPUT,
  __module__ = 'terminal_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.TerminalOutput)
  ))
_sym_db.RegisterMessage(TerminalOutput)

TerminalInput = _reflection.GeneratedProtocolMessageType('TerminalInput', (_message.Message,), dict(
  DESCRIPTOR = _TERMINALINPUT,
  __module__ = 'terminal_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.TerminalInput)
  ))
_sym_db.RegisterMessage(TerminalInput)

TerminalResize = _reflection.GeneratedProtocolMessageType('TerminalResize', (_message.Message,), dict(
  DESCRIPTOR = _TERMINALRESIZE,
  __module__ = 'terminal_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.TerminalResize)
  ))
_sym_db.RegisterMessage(TerminalResize)

SessionRequest = _reflection.GeneratedProtocolMessageType('SessionRequest', (_message.Message,), dict(
  DESCRIPTOR = _SESSIONREQUEST,
  __module__ = 'terminal_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.SessionRequest)
  ))
_sym_db.RegisterMessage(SessionRequest)


_STARTTERMINALREQUEST_ENVENTRY.has_options = True
_STARTTERMINALREQUEST_ENVENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_TERMINALSERVICE = _descriptor.ServiceDescriptor(
  name='TerminalService',
  full_name='rqt2.api.v1.TerminalService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=618,
  serialized_end=965,
  methods=[
  _descriptor.MethodDescriptor(
    name='Start',
    full_name='rqt2.api.v1.TerminalService.Start',
    index=0,
    containing_service=None,
    input_type=_STARTTERMINALREQUEST,
    output_type=_STARTTERMINALRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Attach',
    full_name='rqt2.api.v1.TerminalService.Attach',
    index=1,
    containing_service=None,
    input_type=_ATTACHREQUEST,
    output_type=_TERMINALOUTPUT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendInput',
    full_name='rqt2.api.v1.TerminalService.SendInput',
    index=2,
    containing_service=None,
    input_type=_TERMINALINPUT,
    output_type=types__pb2._STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Resize',
    full_name='rqt2.api.v1.TerminalService.Resize',
    index=3,
    containing_service=None,
    input_type=_TERMINALRESIZE,
    output_type=types__pb2._STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Close',
    full_name='rqt2.api.v1.TerminalService.Close',
    index=4,
    containing_service=None,
    input_type=_SESSIONREQUEST,
    output_type=types__pb2._STATUS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TERMINALSERVICE)

DESCRIPTOR.services_by_name['TerminalService'] = _TERMINALSERVICE

# @@protoc_insertion_point(module_scope)
