# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import terminal_pb2 as terminal__pb2
import types_pb2 as types__pb2


class TerminalServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Start = channel.unary_unary(
        '/rqt2.api.v1.TerminalService/Start',
        request_serializer=terminal__pb2.StartTerminalRequest.SerializeToString,
        response_deserializer=terminal__pb2.StartTerminalResponse.FromString,
        )
    self.Attach = channel.unary_stream(
        '/rqt2.api.v1.TerminalService/Attach',
        request_serializer=terminal__pb2.AttachRequest.SerializeToString,
        response_deserializer=terminal__pb2.TerminalOutput.FromString,
        )
    self.SendInput = channel.unary_unary(
        '/rqt2.api.v1.TerminalService/SendInput',
        request_serializer=terminal__pb2.TerminalInput.SerializeToString,
        response_deserializer=types__pb2.Status.FromString,
        )
    self.Resize = channel.unary_unary(
        '/rqt2.api.v1.TerminalService/Resize',
        request_serializer=terminal__pb2.TerminalResize.SerializeToString,
        response_deserializer=types__pb2.Status.FromString,
        )
    self.Close = channel.unary_unary(
        '/rqt2.api.v1.TerminalService/Close',
        request_serializer=terminal__pb2.SessionRequest.SerializeToString,
        response_deserializer=types__pb2.Status.FromString,
        )


class TerminalServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Start(self, request, context):
    """Starts a new PTY-backed terminal session (server will spawn a shell)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Attach(self, request, context):
    """Attach to an existing session and receive output as a stream
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendInput(self, request, context):
    """Send input bytes to a running session
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Resize(self, request, context):
    """Resize PTY
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Close(self, request, context):
    """Close session
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TerminalServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Start': grpc.unary_unary_rpc_method_handler(
          servicer.Start,
          request_deserializer=terminal__pb2.StartTerminalRequest.FromString,
          response_serializer=terminal__pb2.StartTerminalResponse.SerializeToString,
      ),
      'Attach': grpc.unary_stream_rpc_method_handler(
          servicer.Attach,
          request_deserializer=terminal__pb2.AttachRequest.FromString,
          response_serializer=terminal__pb2.TerminalOutput.SerializeToString,
      ),
      'SendInput': grpc.unary_unary_rpc_method_handler(
          servicer.SendInput,
          request_deserializer=terminal__pb2.TerminalInput.FromString,
          response_serializer=types__pb2.Status.SerializeToString,
      ),
      'Resize': grpc.unary_unary_rpc_method_handler(
          servicer.Resize,
          request_deserializer=terminal__pb2.TerminalResize.FromString,
          response_serializer=types__pb2.Status.SerializeToString,
      ),
      'Close': grpc.unary_unary_rpc_method_handler(
          servicer.Close,
          request_deserializer=terminal__pb2.SessionRequest.FromString,
          response_serializer=types__pb2.Status.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rqt2.api.v1.TerminalService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
