# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import types_pb2 as types__pb2
import workspace_pb2 as workspace__pb2


class WorkspaceServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.OpenWorkspace = channel.unary_unary(
        '/rqt2.api.v1.WorkspaceService/OpenWorkspace',
        request_serializer=workspace__pb2.OpenWorkspaceRequest.SerializeToString,
        response_deserializer=workspace__pb2.OpenWorkspaceResponse.FromString,
        )
    self.ListPackages = channel.unary_unary(
        '/rqt2.api.v1.WorkspaceService/ListPackages',
        request_serializer=workspace__pb2.ListPackagesRequest.SerializeToString,
        response_deserializer=workspace__pb2.ListPackagesResponse.FromString,
        )
    self.CreatePackage = channel.unary_unary(
        '/rqt2.api.v1.WorkspaceService/CreatePackage',
        request_serializer=workspace__pb2.CreatePackageRequest.SerializeToString,
        response_deserializer=types__pb2.Status.FromString,
        )


class WorkspaceServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def OpenWorkspace(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListPackages(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreatePackage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WorkspaceServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'OpenWorkspace': grpc.unary_unary_rpc_method_handler(
          servicer.OpenWorkspace,
          request_deserializer=workspace__pb2.OpenWorkspaceRequest.FromString,
          response_serializer=workspace__pb2.OpenWorkspaceResponse.SerializeToString,
      ),
      'ListPackages': grpc.unary_unary_rpc_method_handler(
          servicer.ListPackages,
          request_deserializer=workspace__pb2.ListPackagesRequest.FromString,
          response_serializer=workspace__pb2.ListPackagesResponse.SerializeToString,
      ),
      'CreatePackage': grpc.unary_unary_rpc_method_handler(
          servicer.CreatePackage,
          request_deserializer=workspace__pb2.CreatePackageRequest.FromString,
          response_serializer=types__pb2.Status.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rqt2.api.v1.WorkspaceService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
