# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workspace.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='workspace.proto',
  package='rqt2.api.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x0fworkspace.proto\x12\x0brqt2.api.v1\x1a\x0btypes.proto\"$\n\x14OpenWorkspaceRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"=\n\x0bPackageInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x12\n\nbuild_type\x18\x03 \x01(\t\"h\n\x15OpenWorkspaceResponse\x12*\n\x08packages\x18\x01 \x03(\x0b\x32\x18.rqt2.api.v1.PackageInfo\x12#\n\x06status\x18\x02 \x01(\x0b\x32\x13.rqt2.api.v1.Status\"-\n\x13ListPackagesRequest\x12\x16\n\x0eworkspace_path\x18\x01 \x01(\t\"g\n\x14ListPackagesResponse\x12*\n\x08packages\x18\x01 \x03(\x0b\x32\x18.rqt2.api.v1.PackageInfo\x12#\n\x06status\x18\x02 \x01(\x0b\x32\x13.rqt2.api.v1.Status\"\xc1\x01\n\x14\x43reatePackageRequest\x12\x16\n\x0eworkspace_path\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nbuild_type\x18\x03 \x01(\t\x12?\n\x07options\x18\x04 \x03(\x0b\x32..rqt2.api.v1.CreatePackageRequest.OptionsEntry\x1a.\n\x0cOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x88\x02\n\x10WorkspaceService\x12V\n\rOpenWorkspace\x12!.rqt2.api.v1.OpenWorkspaceRequest\x1a\".rqt2.api.v1.OpenWorkspaceResponse\x12S\n\x0cListPackages\x12 .rqt2.api.v1.ListPackagesRequest\x1a!.rqt2.api.v1.ListPackagesResponse\x12G\n\rCreatePackage\x12!.rqt2.api.v1.CreatePackageRequest\x1a\x13.rqt2.api.v1.Statusb\x06proto3')
  ,
  dependencies=[types__pb2.DESCRIPTOR,])




_OPENWORKSPACEREQUEST = _descriptor.Descriptor(
  name='OpenWorkspaceRequest',
  full_name='rqt2.api.v1.OpenWorkspaceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='rqt2.api.v1.OpenWorkspaceRequest.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=81,
)


_PACKAGEINFO = _descriptor.Descriptor(
  name='PackageInfo',
  full_name='rqt2.api.v1.PackageInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rqt2.api.v1.PackageInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='rqt2.api.v1.PackageInfo.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_type', full_name='rqt2.api.v1.PackageInfo.build_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=144,
)


_OPENWORKSPACERESPONSE = _descriptor.Descriptor(
  name='OpenWorkspaceResponse',
  full_name='rqt2.api.v1.OpenWorkspaceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packages', full_name='rqt2.api.v1.OpenWorkspaceResponse.packages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='rqt2.api.v1.OpenWorkspaceResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=250,
)


_LISTPACKAGESREQUEST = _descriptor.Descriptor(
  name='ListPackagesRequest',
  full_name='rqt2.api.v1.ListPackagesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workspace_path', full_name='rqt2.api.v1.ListPackagesRequest.workspace_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=297,
)


_LISTPACKAGESRESPONSE = _descriptor.Descriptor(
  name='ListPackagesResponse',
  full_name='rqt2.api.v1.ListPackagesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packages', full_name='rqt2.api.v1.ListPackagesResponse.packages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='rqt2.api.v1.ListPackagesResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=402,
)


_CREATEPACKAGEREQUEST_OPTIONSENTRY = _descriptor.Descriptor(
  name='OptionsEntry',
  full_name='rqt2.api.v1.CreatePackageRequest.OptionsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='rqt2.api.v1.CreatePackageRequest.OptionsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='rqt2.api.v1.CreatePackageRequest.OptionsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=552,
  serialized_end=598,
)

_CREATEPACKAGEREQUEST = _descriptor.Descriptor(
  name='CreatePackageRequest',
  full_name='rqt2.api.v1.CreatePackageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workspace_path', full_name='rqt2.api.v1.CreatePackageRequest.workspace_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='rqt2.api.v1.CreatePackageRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_type', full_name='rqt2.api.v1.CreatePackageRequest.build_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='options', full_name='rqt2.api.v1.CreatePackageRequest.options', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CREATEPACKAGEREQUEST_OPTIONSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=598,
)

_OPENWORKSPACERESPONSE.fields_by_name['packages'].message_type = _PACKAGEINFO
_OPENWORKSPACERESPONSE.fields_by_name['status'].message_type = types__pb2._STATUS
_LISTPACKAGESRESPONSE.fields_by_name['packages'].message_type = _PACKAGEINFO
_LISTPACKAGESRESPONSE.fields_by_name['status'].message_type = types__pb2._STATUS
_CREATEPACKAGEREQUEST_OPTIONSENTRY.containing_type = _CREATEPACKAGEREQUEST
_CREATEPACKAGEREQUEST.fields_by_name['options'].message_type = _CREATEPACKAGEREQUEST_OPTIONSENTRY
DESCRIPTOR.message_types_by_name['OpenWorkspaceRequest'] = _OPENWORKSPACEREQUEST
DESCRIPTOR.message_types_by_name['PackageInfo'] = _PACKAGEINFO
DESCRIPTOR.message_types_by_name['OpenWorkspaceResponse'] = _OPENWORKSPACERESPONSE
DESCRIPTOR.message_types_by_name['ListPackagesRequest'] = _LISTPACKAGESREQUEST
DESCRIPTOR.message_types_by_name['ListPackagesResponse'] = _LISTPACKAGESRESPONSE
DESCRIPTOR.message_types_by_name['CreatePackageRequest'] = _CREATEPACKAGEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OpenWorkspaceRequest = _reflection.GeneratedProtocolMessageType('OpenWorkspaceRequest', (_message.Message,), dict(
  DESCRIPTOR = _OPENWORKSPACEREQUEST,
  __module__ = 'workspace_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.OpenWorkspaceRequest)
  ))
_sym_db.RegisterMessage(OpenWorkspaceRequest)

PackageInfo = _reflection.GeneratedProtocolMessageType('PackageInfo', (_message.Message,), dict(
  DESCRIPTOR = _PACKAGEINFO,
  __module__ = 'workspace_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.PackageInfo)
  ))
_sym_db.RegisterMessage(PackageInfo)

OpenWorkspaceResponse = _reflection.GeneratedProtocolMessageType('OpenWorkspaceResponse', (_message.Message,), dict(
  DESCRIPTOR = _OPENWORKSPACERESPONSE,
  __module__ = 'workspace_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.OpenWorkspaceResponse)
  ))
_sym_db.RegisterMessage(OpenWorkspaceResponse)

ListPackagesRequest = _reflection.GeneratedProtocolMessageType('ListPackagesRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTPACKAGESREQUEST,
  __module__ = 'workspace_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.ListPackagesRequest)
  ))
_sym_db.RegisterMessage(ListPackagesRequest)

ListPackagesResponse = _reflection.GeneratedProtocolMessageType('ListPackagesResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTPACKAGESRESPONSE,
  __module__ = 'workspace_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.ListPackagesResponse)
  ))
_sym_db.RegisterMessage(ListPackagesResponse)

CreatePackageRequest = _reflection.GeneratedProtocolMessageType('CreatePackageRequest', (_message.Message,), dict(

  OptionsEntry = _reflection.GeneratedProtocolMessageType('OptionsEntry', (_message.Message,), dict(
    DESCRIPTOR = _CREATEPACKAGEREQUEST_OPTIONSENTRY,
    __module__ = 'workspace_pb2'
    # @@protoc_insertion_point(class_scope:rqt2.api.v1.CreatePackageRequest.OptionsEntry)
    ))
  ,
  DESCRIPTOR = _CREATEPACKAGEREQUEST,
  __module__ = 'workspace_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.CreatePackageRequest)
  ))
_sym_db.RegisterMessage(CreatePackageRequest)
_sym_db.RegisterMessage(CreatePackageRequest.OptionsEntry)


_CREATEPACKAGEREQUEST_OPTIONSENTRY.has_options = True
_CREATEPACKAGEREQUEST_OPTIONSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_WORKSPACESERVICE = _descriptor.ServiceDescriptor(
  name='WorkspaceService',
  full_name='rqt2.api.v1.WorkspaceService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=601,
  serialized_end=865,
  methods=[
  _descriptor.MethodDescriptor(
    name='OpenWorkspace',
    full_name='rqt2.api.v1.WorkspaceService.OpenWorkspace',
    index=0,
    containing_service=None,
    input_type=_OPENWORKSPACEREQUEST,
    output_type=_OPENWORKSPACERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListPackages',
    full_name='rqt2.api.v1.WorkspaceService.ListPackages',
    index=1,
    containing_service=None,
    input_type=_LISTPACKAGESREQUEST,
    output_type=_LISTPACKAGESRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreatePackage',
    full_name='rqt2.api.v1.WorkspaceService.CreatePackage',
    index=2,
    containing_service=None,
    input_type=_CREATEPACKAGEREQUEST,
    output_type=types__pb2._STATUS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKSPACESERVICE)

DESCRIPTOR.services_by_name['WorkspaceService'] = _WORKSPACESERVICE

# @@protoc_insertion_point(module_scope)
